# Outside of this repository
name: "Github Actions Scenario - Artifact Upload with PR Comment"
on:
  pull_request:
    types: ["opened", "edited", "synchronize"]

jobs:
  artifact-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Example Project
        run: | 
          echo "Building Artifact..."
          touch artifact.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./
          name: artifact.txt
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Please Review Artifact located at: <LINK HERE>'
              })