# Outside of this repository
name: "Github Actions Scenario - Artifact Upload with PR Comment"
on:
  pull_request:
    types: ["opened", "edited", "synchronize"]

env:
  artifact-name: artifact.txt

jobs:
  artifact-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Example Project
        run: | 
          echo "Building Artifact..."
          touch ${{ env.artifact-name }} 
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          path: ./
          name: ${{ env.artifact-name }} 
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            const artifactLink = `${{ steps.upload-artifact.outputs.artifact-url }}`
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Please Review Artifact located [here](${artifactLink})\nLink for Debugging: ${artifactLink}`
              })